#!/bin/zsh

DEBUG=0
if [[ $1 = (-|)-debug ]]
then
  DEBUG=1
fi

run_command()
{
  if [[ $DEBUG -eq 1 ]]
  then
    echo Running: $@
    "$@" 
  else
    "$@" 1>/dev/null 2>/dev/null
  fi
}

run_command /usr/bin/git fetch
run_command /usr/bin/git merge origin/master master
run_command /usr/bin/strfile /home/bernard/BOWQuotes/quotes.txt
run_command echo "Your Daily Quote Dosage!"
run_command echo ""
run_command /usr/games/fortune /home/bernard/BOWQuotes/quotes.txt
